dashboard:
  pattern:  /dashboard
  defaults: { _controller: ECommerceBundle:ECommerce:dashboard }

products:
  pattern:  /products
  defaults: { _controller: ProductBundle:Product:index }

product_show:
  pattern:  /product/:id
  defaults: { _controller: ProductBundle:Product:show }


