imports:
  - { resource: config.yml }

app.config:
  toolbar: false
  test: {}

zend.config:
  logger:
    priority: debug

doctrine.dbal:
  connections:
    default:
      driver:               PDOSqlite
      path:                 %kernel.cache_dir%/OrderTests.sqlite

test_session.config: ~

