imports:
  - { resource: config.yml }

web.config:
  toolbar: false

zend.logger:
  priority: debug
  path:     %kernel.root_dir%/logs/%kernel.environment%.log

doctrine.dbal:
  connections:
    default:
      driver:               PDOSqlite
      path:                 %kernel.cache_dir%/OrderTests.sqlite

kernel.test: ~
test_session.config: ~

