imports:
  - { resource: config.yml }

app.config:
  router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
  profiler: { only_exceptions: false }
  toolbar: true
  intercept_redirects: true

webprofiler.config:
  toolbar: true

zend.config:
  logger:
    priority: debug
    path:     %kernel.root_dir%/logs/%kernel.environment%.log

doctrine_odm.mongodb: ~

mongo_admin.config:
  servers:
    localhost: localhost:27017

twig.config:
  auto_reload: true
