imports:
    - { resource: config_dev.yml }

web.config:
    toolbar: false

zend.logger:
    priority: debug

doctrine.dbal:
  connections:
    default:
      driver:               PDOSqlite
      path:                 %kernel.cache_dir%/OrderTests.sqlite

kernel.test: ~
