
_esi:
  resource:  "FrameworkBundle/Resources/config/routing/internal.xml"
  prefix:    "/_esi"
  
_profiler:
  resource: WebProfilerBundle/Resources/config/routing/profiler.xml
  prefix:   /_profiler

homepage:
    pattern:  /
    defaults: { _controller: ECommerceBundle:ECommerce:index }

eCommerce:
    resource: ECommerceBundle/Resources/config/routing.yml
