
_security_login:
  pattern: /login
  defaults: { _controller: ECommerceBundle:ECommerce:login }

_security_check:
  pattern: /login_check

_esi:
  resource:  FrameworkBundle/Resources/config/routing/internal.xml
  prefix:    /_esi
  
_profiler:
  resource: WebProfilerBundle/Resources/config/routing/profiler.xml
  prefix:   /_profiler

homepage:
  pattern:  /
  defaults: { _controller: ECommerceBundle:ECommerce:index }

eCommerce:
  resource: ECommerceBundle/Resources/config/routing.yml

contact:
  resource: ContactBundle/Resources/config/routing.xml
