_main:
  resource: routing.yml

_profiler:
  resource: WebProfilerBundle/Resources/config/routing/profiler.xml
  prefix:   /_profiler

mongo_admin:
  resource: MongoAdminBundle/Resources/config/routing.yml
  prefix: admin
