
_esi:
  resource:  "FrameworkBundle/Resources/config/internal_routing.xml"
  prefix:    "/_esi"

homepage:
    pattern:  /
    defaults: { _controller: ECommerceBundle:ECommerce:index }

eCommerce:
    resource: ECommerceBundle/Resources/config/routing.yml
